---
title: "Data Management Plan - DECISION22"
author: "Matthew Grainger"
date: "1 2 2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Project Information

Project: *DECISION22: Advancing Evidence Synthesis Toolchains for Conservation Decision Making*  
Website: *https://github.com/DrMattG/DECISION22*  
PI: *Dr Matthew Grainger*


## Table of Contents:     
[Data Management Plan and other Documentation](#data-management-plan-and-other-documentation)  
[Data Management Units](#data-management-units)  
[Data Collection](#data-collection)  
[Data Documentation](#data-documentation)  
[File Organisation](#file-organization)  
[Formats](#formats)  
[Storage](#storage)  
[Backup](#backup)  
[Workflow Internal Data Sharing](#workflow-internal-data-sharing)  
[Data Use](#data-use)  
[Protection for Sensitive and Confidential Data](#protection-for-sensitive-and-confidential-data)  
[Data Publication](#data-publication)  
[Data Archival](#data-archival)  
[Roles and Responsibilities](#roles-and-responsibilities)  

## Data Management Plan and other Documentation

- 	The data management plan that was submitted with the grant proposal for this project can be found in *DOI:10.17605/OSF.IO/2S5RV*  
- The Research Council of Norway (NRF) is member organisation of PlanS *https://www.forskningsradet.no/forskningspolitisk-radgivning/apen-forskning/apen-tilgang-til-publikasjoner/* and hence all research funded through the NRF adhere to open access publishing principles. 

## Data Management Units


*Three* groups of datasets will be generated during the course of this project.

1. Dataset Group 1 *Simulated dataset to exploring missing data in network meta-analysis*  
	Type of dataset: *Simulation*  
	Collection strategy: *Data will be generated in R using bespoke functions*  
	Amount of data expected: *10000 rows*  

2. Dataset Group 2 *Marine Protected Areas*  
	Type of dataset: *Extracted effect sizes and metadata from published meta-analyses on the effectiveness of Marine Protected Areas*  
	Collection strategy: *Systematic Review*  
	Amount of data expected: *At least 16 published meta-analyses*  
	
3. Dataset Group 3 *Grouse fence collisions*  
	Type of dataset: *Extracted effect sizes and metadata from published papers and unpublished reports on the effectiveness of fence markers on grouse survival*  
	Collection strategy: *Systematic Review*  
	Amount of data expected: *At least 4 published papers*  


## Data Collection

**Development of protocols:**   

1.  Process *Protocols for the development of the two case studies will be developed using the Environmental Evidence template: https://environmentalevidencejournal.biomedcentral.com/submission-guidelines/preparing-your-manuscript/systematic-review-protocol*  
2. Approval *The proposal will be approved by the project team (Matthew Grainger, Erlend Nilsen, Gavin Stewart and Charles Gray)*  
3. Storage *The protocols will be stored on the OSF repository (DOI:10.17605/OSF.IO/2S5RV) *  
4. Update *Updates to protocols will be recorded using version control in the OSF repository so that we can track the changes made in the document*  

**Software:** *The project will be mainly focused on the R environment for statistical computing (https://www.R-project.org/). All code will be archived on the GitHub repository https://github.com/DrMattG/DECISION22*  

## Data Documentation

Data will be documented throughout the research process using the following tools:

**ROxygen2:** *Data will be documented using ROxygen2 using the sinew package in R (https://github.com/yonicd/sinew)*

**EML metadata** *Metadata will be produced for each dataset in the Ecological MArkdown Language*

## File Organization

## Formats
   
*Data will be stored in persistent formats (.csv, .txt) as well as objects in .RDS stored in on the OSF repository (DOI:10.17605/OSF.IO/2S5RV)*


## Storage  

*Data will be stored on the OSF repository (DOI:10.17605/OSF.IO/2S5RV)* 


## Backup
*Data will be version controlled on the OSF repository (DOI:10.17605/OSF.IO/2S5RV). In addition, data will be stored locally on the NINA servers.*


## Workflow Internal Data Sharing
*Project participants will interact using GitHub issues and the Discussion forum on GitHub (https://github.com/DrMattG/DECISION22). All participants will have access to the public OSF repository (DOI:10.17605/OSF.IO/2S5RV)*

## Data Use
*A CC-By Attribution license allows data use by others as long as the original data creators are acknowledged*

## Protection for Sensitive and Confidential Data

*We do not expect to acquire any sensitive or confidential data. However, in the case that we do then we will ensure that any identifying data are encrypted securely*

## Data Publication
*Data will be publicly available (at DOI:10.17605/OSF.IO/2S5RV). The case study data will also be published using EviAtlas (https://www.eshackathon.org/software/eviatlas.html) and displayed publicly from the NINA Shiny Server*

## Roles and Responsibilities

**DMP Implementation:** responsible for ensuring Data Management Plan and the Internal Data Sharing Plan move from planning into implementation; ensure that any practices, responsibilities, policies outlined in the plan are followed; ensure that new members of the Project will receive data management training; responsible for maintaining the Data Management Plan and the Internal Data Sharing Plan up to date, and making sure that all members of the Project understand and are prepared to apply the changes.


 Responsibility of: **Principle Investigator (PI) Matthew Grainger**


**Protection of sensitive and protected data:** responsible for complying with applicable laws and regulations, institutional policies, and ethical principles governing the conduct of human subjects research, sensitive and protected data.


Responsibility of: **Principle Investigator (PI) Matthew Grainger**

**Data collection/ data generation:** responsible for data collection and creation (research, locate, identify, and measure), data entry, information processing (transcribing and manipulation), data generation (prototyping, models, and database).

Responsibility of: **Principle Investigator (PI) Matthew Grainger**